### ISSUE TITLE
Tenderbake support in Signatory

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/signatory#144]

**Comment by GImbrailo** [comment]
We deployed `tenderbake` with signatory and ran into some errors. Here are the logs after signatory was running

```shell
time="2021-11-09T05:21:49Z" level=info msg="Initializing vault" vault=file vault_name=local_file_keys
time="2021-11-09T05:21:49Z" level=info msg="HTTP server is listening for connections on :6732"
time="2021-11-09T05:21:49Z" level=info msg="Utility HTTP server is listening for connections on :9583"
time="2021-11-09T15:11:23Z" level=info msg="GET /authorized_keys" duration=1.286876ms hostname="signatory:6732" method=GET path=/authorized_keys start_time="2021-11-09T15:11:23Z" status=200
time="2021-11-09T15:11:23Z" level=error msg="tezos: unknown watermark tag: 18" pkh=tz1cjyja1TU6fiyiFav3mFAdnDsCReJ12hPD raw=12ed9d217c2f50673bab6b20dfb0a88ca93b4a0c72a34c807af5dffbece2cba3d2b509835f14006000000002000000041f1ebb39759cc957216f88fb4d005abc206fb00a53f8d57ac01be00c084cba97
time="2021-11-09T15:11:23Z" level=error msg="Error signing request: tezos: unknown watermark tag: 18"
time="2021-11-09T15:11:23Z" level=info msg="POST /keys/tz1cjyja1TU6fiyiFav3mFAdnDsCReJ12hPD" duration=4.334053ms hostname="signatory:6732" method=POST path=/keys/tz1cjyja1TU6fiyiFav3mFAdnDsCReJ12hPD start_time="2021-11-09T15:11:23Z" status=400
time="2021-11-09T15:12:42Z" level=info msg="GET /authorized_keys" duration="136.952µs" hostname="signatory:6732" method=GET path=/authorized_keys start_time="2021-11-09T15:12:42Z" status=200
time="2021-11-09T15:12:42Z" level=error msg="tezos: unknown watermark tag: 18" pkh=tz1cjyja1TU6fiyiFav3mFAdnDsCReJ12hPD raw=12ed9d217c2f50673bab6b20dfb0a88ca93b4a0c72a34c807af5dffbece2cba3d2b509835f1400600000000200000005554ff14bf2d6f40d0176221a6eaa385e7fcefe272063bf9d156baf5da3a0a012
time="2021-11-09T15:12:42Z" level=error msg="Error signing request: tezos: unknown watermark tag: 18"
time="2021-11-09T15:12:42Z" level=info msg="POST /keys/tz1cjyja1TU6fiyiFav3mFAdnDsCReJ12hPD" duration="472.287µs" hostname="signatory:6732" method=POST path=/keys/tz1cjyja1TU6fiyiFav3mFAdnDsCReJ12hPD start_time="2021-11-09T15:12:42Z" status=400
``` 
Our `signatory.yml` file has the following configuration
```yaml
server:
  # Address/Port that Signatory listens on
  address: :6732
  # Address/Port that Signatory serves prometheus metrics on
  utility_address: :9583

vaults:
# Name of vault
  local_file_keys:
    driver: file
    config:
      file: /etc/signatory/secret.json

# List enabled public keys hashes here
tezos:
  # Default policy allows "block" and "endorsement" operations
  tz1cjyja1TU6fiyiFav3mFAdnDsCReJ12hPD:
    log_payloads: true
    allowed_operations:
    # List of [generic, block, endorsement]
    - generic
    - block
    - endorsement
    allowed_kinds:
      - reveal
      - transaction
      - delegation 
```

We also noticed that there is a new file in the `tezos_client` directory called `NetXxkAx4woPL_highwatermarks` with the following contents:
```json
{ "blocks":
    [ { "delegate": "tz1cjyja1TU6fiyiFav3mFAdnDsCReJ12hPD",
        "highwatermark": { "round": 1, "level": 277 } } ],
  "preendorsements":
    [ { "delegate": "tz1cjyja1TU6fiyiFav3mFAdnDsCReJ12hPD",
        "highwatermark": { "round": 1, "level": 293 } } ],
  "endorsements":
    [ { "delegate": "tz1cjyja1TU6fiyiFav3mFAdnDsCReJ12hPD",
        "highwatermark": { "round": 1, "level": 293 } } ] }
```
