### ISSUE TITLE
`ledger list` command for signatory-cli will not show ledger information

### ISSUE THREAD

**Issue by alexzbusko** [ecadlabs/signatory#163]
After cloning the signatory repo and running `make` to create both the signatory and signatory-cli binaries when you run the `signatory-cli ledger list -c signatory.yaml` it will initialize the vault but not print out any information about the ledger. This is what gets the ID that the signatory.yaml file will use to target the ledger device

Steps to reproduce:

1. Clone the signatory repo and cd into the signatory directory
2. Run the command `make`
3. Create/modify the signatory.yaml file with the following information in it:
```
server:
  # Address/Port that Signatory listens on
  address: :6732
  # Address/Port that Signatory serves prometheus metrics on
  utility_address: :9583

vaults:
# Name of vault
  ledger:
    driver: ledger
    config:
      keys:
        - "bip32-ed25519/0'/0'"
        - "secp256k1/0'/1'"
      close_after: 600800s
```
4. Run the command './signatory-cli ledger list -c signatory.yaml'

Expected Result:
```
$ ./signatory-cli ledger list -c signatory.yaml
INFO[0000] Initializing vault                            vault=ledger vault_name=ledger
Path:           0001:0007:00
ID:             tz1bjnGUjZFH22QSag2dyiKR5P6y24iKoTQx / b0997791
Version:        TezBake 2.2.13
```

Actual Result:
```
$ ./signatory-cli ledger list -c signatory.yaml
INFO[0000] Initializing vault                            vault=ledger vault_name=ledger
```
