### ISSUE TITLE
AWS KMS vault errors with invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by danielelisi** [ecadlabs/signatory#171]
I'm testing the AWS KMS support from #143.  I created a new key via AWS KMS UI and configured Signatory to use it. However when I test querying the key with `$ curl localhost:6733/keys/tz2PL6o4YoSKRVxbqvVY2JCL3aKGoD3BWTw7`  I receive the following error
```
time="2022-03-10T13:00:01Z" level=info msg="Initializing vault" vault=awskms vault_name=aws_kms
time="2022-03-10T13:00:01Z" level=info msg="HTTP server is listening for connections on :6733"
time="2022-03-10T13:00:01Z" level=info msg="Utility HTTP server is listening for connections on :9583"
2022/03/10 13:03:55 http: panic serving 172.17.0.1:55794: runtime error: invalid memory address or nil pointer dereference
goroutine 23 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1802 +0xb9
panic({0xce2c40, 0x17cc640})
	/usr/local/go/src/runtime/panic.go:1047 +0x266
github.com/ecadlabs/signatory/pkg/signatory.(*Signatory).listPublicKeys(0xc00021a060, {0x1180190, 0xc0002ee510})
	/home/dan/signatory/pkg/signatory/signatory.go:304 +0x187
github.com/ecadlabs/signatory/pkg/signatory.(*Signatory).getPublicKey(0xc00021a060, {0x1180190, 0xc0002ee510}, {0xc00031c14a, 0x24})
	/home/dan/signatory/pkg/signatory/signatory.go:359 +0x133
github.com/ecadlabs/signatory/pkg/signatory.(*Signatory).GetPublicKey(0xc00021a060, {0x1180190, 0xc0002ee510}, {0xc00031c14a, 0x24})
	/home/dan/signatory/pkg/signatory/signatory.go:372 +0x45
github.com/ecadlabs/signatory/pkg/server.(*Server).getKeyHandler(0xc000031ec0, {0x7f3895810bb8, 0xc00000c270}, 0xc00008f500)
	/home/dan/signatory/pkg/server/server.go:135 +0x94
net/http.HandlerFunc.ServeHTTP(0xc0002137b8, {0x7f3895810bb8, 0xc00000c270}, 0x0)
	/usr/local/go/src/net/http/server.go:2047 +0x2f
github.com/ecadlabs/signatory/pkg/server.(*Logging).Handler.func1({0x117c050, 0xc0003d61c0}, 0xc00008f500)
	/home/dan/signatory/pkg/server/middleware.go:82 +0x191
net/http.HandlerFunc.ServeHTTP(0xc00008f400, {0x117c050, 0xc0003d61c0}, 0xdcfc00)
	/usr/local/go/src/net/http/server.go:2047 +0x2f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc00027a3c0, {0x117c050, 0xc0003d61c0}, 0xc00008f300)
	/home/dan/go/pkg/mod/github.com/gorilla/mux@v1.7.3/mux.go:212 +0x202
net/http.serverHandler.ServeHTTP({0xc0002ee180}, {0x117c050, 0xc0003d61c0}, 0xc00008f300)
	/usr/local/go/src/net/http/server.go:2879 +0x43b
net/http.(*conn).serve(0xc0002ce000, {0x1180190, 0xc0002eea50})
	/usr/local/go/src/net/http/server.go:1930 +0xb08
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3034 +0x4e8
```

This is my Signatory config file
```yaml
server:
  address: :6733
  utility_address: :9583

vaults:
  aws_kms:
    driver: awskms
    config: 
      user_name: 'signatory-aws-kms'
      kms_key_id: 'bdfb3199-2716-49d4-8564-faf8260e3200'
      access_key_id: '<redacted>'
      secret_access_key: '<redacted>'
      region: 'us-west-2'

tezos:
  tz2PL6o4YoSKRVxbqvVY2JCL3aKGoD3BWTw7:
    log_payloads: true
    allowed_operations:
      - generic
      - block
      - endorsement
      - preendorsement
    allowed_kinds:
      - reveal
      - transaction
      - delegation
```

I derived the Tezos public key hash `tz2PL6o4YoSKRVxbqvVY2JCL3aKGoD3BWTw7` from the KMS public key by using https://github.com/tacoinfra/tezos-kms
