### ISSUE TITLE
move "allowed_kinds" under the "generic" item in config

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/signatory#187]
Present:
```yaml
tezos:
  # signatory_file_baker
  tz1TAuZaNgQz3GpQVLegbNC8V9vWoGzsQcWB:
    log_payloads: true
    allowed_operations:
      - generic
      - block
      - endorsement
      - preendorsement
    allowed_kinds:
      - reveal
      - transaction
      - delegation
```

Proposed:

```yaml
tezos:
  # signatory_file_baker
  tz1TAuZaNgQz3GpQVLegbNC8V9vWoGzsQcWB:
    log_payloads: true
    allowed_operations:
      - generic:
          - reveal
          - transaction
          - delegation
      - block
      - endorsement
      - preendorsement
    allowed_kinds:

```
