### ISSUE TITLE
Michelson parser/AST in go

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/signatory#191]
## Summary

Implement a Michelson parser/AST in Go to enable rich policy rules for smart contract calls. This would allow Signatory to inspect transaction parameters and enforce granular policies beyond simple operation type filtering.

### 1. Entrypoint Allowlist
Only allow calls to specific contract entrypoints:
```yaml
allow:
  generic:
    - transaction:
        entrypoints: [stake, unstake, claim]
```

### 2. Entrypoint Blocklist
Block dangerous entrypoints while allowing others:
```yaml
deny:
  generic:
    - transaction:
        entrypoints: [withdraw_all, emergency_exit]
```

### 3. Parameter Constraints
Limit values in transaction parameters:
```yaml
allow:
  generic:
    - transaction:
        entrypoint: transfer
        constraints:
          - path: $.amount
            max: 10000000000  # max 10k tez
```

### 4. Destination + Entrypoint Combinations
```yaml
allow:
  generic:
    - transaction:
        destination: KT1StakingContract...
        entrypoints: [stake, unstake]
    - transaction:
        destination: KT1GovernanceContract...
        entrypoints: [vote, propose]
```

## Technical Approach

1. Parse Michelson parameters from transaction operations
2. Build AST representation of the parameter data
3. Implement JSONPath-like query language for policy rules
4. Integrate with existing policy engine

## Related Issues

- #60 - Transfer limits: maximum amount/TX
- #61 - Transfer limits: maximum TX/time period
- #62 - Approved destination list
- #63 - Transfer limits: time of day rules
- #64 - Approval groups

## Notes

This is a significant undertaking but would enable enterprise-grade policy control for institutional users managing treasury keys, staking operations, or DeFi interactions.
