### ISSUE TITLE
What is the correct Policy?

### ISSUE THREAD

**Issue by n0price** [ecadlabs/signatory#510]
Dear Signatory Team, 
I appreciate your help to share the correct policy to allow backer duties, voting, delegating,  staking and unstaking and block transaction (ie: draining funds from consensus key). Thank you!

**Comment by michaelkernaghan** [comment]
The format in your signatory.yaml file would be 

 block:
      endorsement:
      preendorsement:
      generic:
        - transaction
        - reveal
        - delegation

You can choose from the policy list for the rest:
         [activate_account, attestation, attestation_with_dal, ballot, dal_publish_commitment, delegation, double_attestation_evidence,  double_baking_evidence, double_preattestation_evidence, drain_delegate, failing_noop, finalize_unstake, increase_paid_storage, origination, preattestation, proposals, register_global_constant, reveal, seed_nonce_revelation, set_delegate_parameters, set_deposits_limit, signature_prefix, smart_rollup_add_messages, smart_rollup_cement, smart_rollup_execute_outbox_message,
smart_rollup_originate, smart_rollup_publish, smart_rollup_recover_bond, smart_rollup_refute, smart_rollup_timeout, stake,
transaction, transfer_ticket, unstake, update_consensus_key, vdf_revelation, zk_rollup_origination, zk_rollup_publish,
zk_rollup_update]

So you might choose:

 block:
      endorsement:
      preendorsement:
      preattestation:
      attestation:
      drain_delegate:
      unstake:
      finalize_unstake:    
      generic:
        - transaction
        - reveal
        - delegation

**Comment by n0price** [comment]
Thanks, so something like this should work to allow baker duties, delegation and staking transactions only.

```
tezos:
  tz1ExamplePublicKeyHash:
    log_payloads: true
    allow:
      endorsement:
        - endorsement
        - preendorsement
      generic:
        - delegation
        - stake
        - unstake
        - ballot
        - reveal 
      block:
        - block
    deny:
      generic:
        - transaction   # Deny general transactions (e.g., Alice sending to Bob)
        - drain_delegate  # Specifically block draining of consensus key
```

**Comment by michaelkernaghan** [comment]
signatory is "closed by default" so there is no 'deny' block.

also, if you have 'unstake' you might want 'finalize_unstake' as well. 

Finally, note as well that `endorsement` is now `attestation`  and  `preendorsement` is now `preattestation`

**Comment by n0price** [comment]
Thanks, the following example now is it correct? 

```yaml
tezos:
  tz1ExamplePublicKeyHash:
    log_payloads: true
    allow:
      block:
      preattestation:
      attestation:
      unstake:
      finalize_unstake:    
      generic:
        - transaction
        - reveal
        - delegation
        - drain_delegate
 ````

**Comment by michaelkernaghan** [comment]
That should work.

**Comment by michaelkernaghan** [comment]
The Ledger hardware wallet provides excellent security for storing the signing key required for baking. It isolates the private key within its secure element, ensuring it cannot be extracted or used outside the Ledger's controlled environment.

**Comment by michaelkernaghan** [comment]
The ledger device must always be connected and active as it signs
attestations and blocks.

**Comment by n0price** [comment]
Thanks. from the documentation I can not understand how does the remote signer really needs to be configured in practice. 
Do we need to have 2 vms, both with the signer installed? one vm has the configuration to connect to the vault to sign the transaction, plus the hook configuration to connect the policy vm the policy configuration. 

So my understanding the setup should something like the following: 

**The signer vm :** 
```
# config root
policy_hook:
    address: host:port
    # List of authorized keys in Tezos Base58 format
    authorized_keys:
        - pub1
        - pub2
        # ...
   
vaults:
  azure:
    driver: azure
    config:
      vault:    
````        


**The policy vm config:**
```
tezos:
  tz1ExamplePublicKeyHash:
    log_payloads: true
    allow:
      block:
      preattestation:
      attestation:
      unstake:
      finalize_unstake:    
      generic:
        - transaction
        - reveal
        - delegation
        - drain_delegate
```


![image](https://github.com/user-attachments/assets/f3b061d9-a528-4605-9c04-9d0a9b72b20a)
