### ISSUE TITLE
Feature Request: Ballot Vote Type Filtering for Protocol Governance

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/signatory#533]
Operators using Signatory for Tezos protocol governance need fine-grained control over which types of votes they authorize for protocol proposals. Currently, Signatory can only allow or disallow ballot operations as a whole, but cannot restrict which vote types (yay/nay/pass) are permitted. This creates a risk where Signatory might unintentionally cast votes against an organization's governance stance.

## Requirements
- Allow operators to configure standing policies that restrict ballot operations to specific vote types
- Support filtering for any combination of "pass", "yay", and "nay" ballot types
- Allow flexible configurations (e.g., only "pass", only "yay" and "nay", all three types, or just one type)
- Enforce these restrictions at the policy level within Signatory
- Provide clear error messages when unauthorized vote types are attempted

## Expected Behaviour
- Operators should be able to configure a public key to only sign specific ballot vote types via YAML configuration
- When a request to sign a ballot comes in, Signatory should verify the vote type against the allowed list
- If the vote type is not explicitly allowed, Signatory should reject the signing request with a clear error
- The policy should persist as a standing rule until explicitly changed

## User Benefits
1. **Governance Compliance**: Organizations can align their signing policy with their governance stance
2. **Flexible Control**: Support for any combination of vote types (pass/yay/nay) to match governance strategy
3. **Risk Mitigation**: Prevents inadvertent casting of votes that conflict with organizational governance policies
4. **Operational Transparency**: Clear documentation of voting stance through explicit configuration
5. **Audit Trail**: Creates clear records of which vote types are permitted for security audits

## Potential config Implementation Example
```yaml
tezos:
  tz1VSUr8wwNhLAzempoch5d6hLRiTh8Cjcjb:
    allow:
      generic:
        - ballot
    allowed_ballot_types:
      - pass  # Only allow "pass" votes
    log_payloads: true
```

With this configuration, the key would only sign "pass" ballots while rejecting any "yay" or "nay" ballot signing requests.

Another example allowing both "yay" and "nay" but not "pass":
```yaml
tezos:
  tz1VSUr8wwNhLAzempoch5d6hLRiTh8Cjcjb:
    allow:
      generic:
        - ballot
    allowed_ballot_types:
      - yay
      - nay
    log_payloads: true
```
