### ISSUE TITLE
Restrict Signing by Magic Byte 

### ISSUE THREAD

**Issue by gaia** [ecadlabs/signatory#67]
Is restricting what type of operation the signer performs (via magic byte) planned for this implementation?

**Comment by jevonearth** [comment]
Yes, the `allowed_operations` if empty causes signatory to deny all by default. Adding types such as `block`, `endoresment`, `preendorsement` will allow those operations only.
```
tezos:
  # Default policy allows "block" and "endorsement" operations
  tz1Wk1Wdczh5BzyZ1uz2DW9xdFg9B5cFuGFm:
    log_payloads: true
    allowed_operations:
    # List of [generic, block, endorsement]
    - generic
    - block
    - endorsement
```
